spring:
  application:
    name: cad-infracoes
  datasource:
    url: jdbc:postgresql://localhost:5432/cad_infracoes
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

api:
  security:
    token:
      secret: ${JWT_SECRET:my-secret-key}

springdoc:
  swagger-ui:
    path: index.html